version: 2

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/typescript-library"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/typescript-library/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/react-router-v7-spa"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/react-router-v7-spa/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/react-router-v7-spa/.github/actions/setup-pull-request-job"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/react-router-v7-ssr"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/react-router-v7-ssr/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/react-router-v7-ssr/.github/actions/setup-pull-request-job"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/next-ssr"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/next-ssr/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/next-ssr/.github/actions/setup-pull-request-job"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/tanstack-router-spa"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/tanstack-router-spa/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/tanstack-router-spa/.github/actions/setup-pull-request-job"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: "/tanstack-start-ssr"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/tanstack-start-ssr/.github/workflows"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: "/tanstack-start-ssr/.github/actions/setup-pull-request-job"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
